Repository identitatem/dex-operator, pull requests merged in 2021-08, with the labels that each got.

#2 update usage with readme
  README.md
Labels: lgtm

#3 add OWNERS and other repo files
  COMPONENT_NAME
  COMPONENT_VERSION
  CONTRIBUTING.md
  LICENSE
  MISSION.md
  OWNERS
  README.md
  RELEASE.md
  SECURITY.md
Labels: lgtm

#4 fix import name
  PROJECT
  controllers/dexconfig_controller.go
  controllers/suite_test.go
  go.mod
  main.go
Labels: lgtm, approved

#8 apply dex CR design to controller
  Makefile
  README.md
  api/v1alpha1/dexclient_types.go
  api/v1alpha1/dexserver_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/auth.identitatem.io_dexclients.yaml
  bundle/manifests/auth.identitatem.io_dexservers.yaml
  bundle/manifests/dex-operator.clusterserviceversion.yaml
  config/crd/bases/auth.identitatem.io_dexclients.yaml
  config/crd/bases/auth.identitatem.io_dexservers.yaml
  config/manager/kustomization.yaml
  config/samples/auth_v1alpha1_dexclient.yaml
  config/samples/auth_v1alpha1_dexserver.yaml
  hack/deployment.yaml
  hack/operator-group.yaml
Labels: approved

#9 refactor and add back dex server logic
  bundle/manifests/dex-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/dexServer.go
  controllers/dexserver_controller.go
  go.mod
  go.sum
  main.go
Labels: approved

#10 add resources seeing log panic
  bundle/manifests/dex-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/dexserver_controller.go
Labels: approved

#11 Use prow dockerfile images
  Dockerfile
Labels: lgtm, approved

#12 force build
  .triggerbuild
Labels: lgtm, approved

#13 implement create secret with Mutual TLS cert and key for server and client
  bundle/manifests/dex-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/dexserver_controller.go
  controllers/mTLS.go
  hack/community/rbac-dex-operator-dexsso-community.yaml
Labels: approved

#16 update k8s api to 4.6
  go.mod
  go.sum
Labels: lgtm, approved

#17 add grpc generated code
  .gitignore
  Makefile2.mak
  go.mod
  go.sum
  pkg/api/api.pb.go
  pkg/api/api.proto
  pkg/api/api_grpc.pb.go
Labels: approved

#19 Add resources.go to get config from mgmt-op
  config/resources.go
  go.mod
  go.sum
Labels: lgtm, approved

#20 Automatically install the crds
  Dockerfile
  config/rbac/role.yaml
  controllers/dexclient_controller.go
  controllers/dexserver_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved

#21 update dexserver with mtls logic
  Dockerfile
  Makefile2.mak
  config/manager/manager.yaml
  controllers/dexserver_controller.go
  controllers/mTLS.go
Labels: approved

#23 add sonar
  sonar-project.properties
Labels: lgtm, approved
